### ISSUE TITLE
Control strength

### ISSUE THREAD

**Issue by wenquanlu** [camenduru/HandRefiner-replicate#2]
Hi, thanks for your great work.

I noticed that on line 68 of predict.py you set strength to 1.0, which as mentioned in the paper, can result in hands losing the textures.

It would be better to use a lower strength like 0.55 (we used it in the paper) or 0.6. (values between 0.4 and 0.8 should be fine)

Thanks!

**Comment by camenduru** [comment]
thanks for the info ❤ slider added 
![image](https://github.com/camenduru/HandRefiner-replicate/assets/54370274/a74c836b-5f9c-4f88-b276-3c190de137c8)

**Comment by wenquanlu** [comment]
That's great! Thank you so much!
